---
kind: pipeline
name: Image Builds 
steps:
- name: Release Images
  privileged: true
  image: alpine
  commands:
  - apk update && apk add git bash curl jq qemu gzip qemu-system-x86_64 qemu-img 
  - apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing packer
  - bash ./build.sh
  environment:
    GITHUB_TOKEN:
      from_secret: "github_api_token"
trigger:
  event:
  - push
  branch:
  - main

node:
  location: glk
