# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "build_version" {
  type = string
}

variable "iso_checksum" {
  type = string
}

variable "version" {
  type = string
}

variable "version_name" {
  type = string
}

variable "accelerator" {
  type = string
  default = "none"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "qemu" "autogenerated_1" {
  accelerator      = "${var.accelerator}"
  boot_wait        = "1s"
  disk_image       = true
  disk_size        = "10000"
  format           = "qcow2"
  headless         = true
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "https://cloud.debian.org/images/cloud/${var.version_name}/${var.build_version}/debian-${var.version}-genericcloud-amd64-${var.build_version}.qcow2"
  output_directory = "tmp"
  qemuargs         = [["-m", "2048M"], ["-smp", "2"], ["-cdrom", "debian/cloud-init/seed.img"]]
  shutdown_command = "sudo sh -c 'userdel -f packer && shutdown now'"
  ssh_password     = "packer"
  ssh_username     = "packer"
  vm_name          = "debian-${var.version} ${var.build_version}.qcow2"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo apt update && sudo apt -y install open-iscsi", "sudo apt install qemu-guest-agent -y && sudo systemctl enable qemu-guest-agent", "ls -lah /etc/udev/rules.d/", "sudo dhclient -r", "echo 'reset cloud-init' && sudo cloud-init clean  &&  sudo rm /etc/machine-id"]
  }

}
