#cloud-config
write_files:
  - encoding: b64
    owner: root:root
    permissions: "0700"
    path: /etc/systemd/system/install.service 
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPUluc3RhbGwgRmxhdGNhcgoKW1NlcnZpY2VdClR5cGU9b25lc2hv
      dApFeGVjU3RhcnQ9L29wdC9pbnN0YWxsLnNoClJlbWFpbkFmdGVyRXhpdD10cnVlClN0YW5kYXJk
      T3V0cHV0PWpvdXJuYWwKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo=
  - encoding: b64
    owner: root:root
    permissions: "0700"
    path: /etc/systemd/system/qemu-ga.service
    content: |
      W1VuaXRdCkRlc2NyaXB0aW9uPU15QXBwCkFmdGVyPWRvY2tlci5zZXJ2aWNlClJlcXVpcmVzPWRv
      Y2tlci5zZXJ2aWNlCgpbU2VydmljZV0KVGltZW91dFN0YXJ0U2VjPTAKRXhlY1N0YXJ0UHJlPS0v
      dXNyL2Jpbi9kb2NrZXIgcm0gLS1mb3JjZSBxZW11LWdhCkV4ZWNTdGFydD0vdXNyL2Jpbi9kb2Nr
      ZXIgcnVuIC0tbmFtZSBxZW11LWdhICAgLS1wcml2aWxlZ2VkICAgLS1uZXQ9aG9zdCAgIC12IC9k
      ZXY6L2RldiAgIC12IC9ldGMvb3MtcmVsZWFzZTovZXRjL29zLXJlbGVhc2U6cm8gIGRvY2tlci5p
      by9kYW5za2FkcmEvcWVtdS1nYSBxZW11LWdhCkV4ZWNTdG9wPS91c3IvYmluL2RvY2tlciBzdG9w
      IHFlbXUtZ2EKUmVzdGFydD1hbHdheXMKUmVzdGFydFNlYz01cwoKW0luc3RhbGxdCldhbnRlZEJ5
      PW11bHRpLXVzZXIudGFyZ2V0Cgo=
  - encoding: b64
    owner: root:root
    permissions: "0700"
    path: /opt/install.sh
    content: | 
      IyEvYmluL3NoCm1vdW50IC1MIENJREFUQSAvbW50Cm1vdW50IC1MIGNpZGF0YSAvbW50CmlmIFsg
      LWYgIi9tbnQvdXNlci1kYXRhIiBdOyB0aGVuCiAgY29yZW9zLWNsb3VkaW5pdCAtLWZyb20tZmls
      ZSAvbW50L3VzZXItZGF0YSAKZmkK
coreos:
    units:
      - name: install.service
        command: start
      - name: qemu-ga.service
        command: start
users:
  - name: core
    passwd: $6$pFoF9DW6921ZuUM8$cDDN68CeyDEobtREPw0HA8eiF2/S0ESwbFPFMxnYfVCjj/THkXOyJz5Rmf6RNoES/KciIXHIsm3l5boyX1bM9.
runcmd:
  - docker pull docker.io/danskadra/qemu-ga
