name: ci

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: install deps & prepair qemu
        run: sudo apt update && sudo apt install -y genisoimage qemu-system-x86 gzip jq qemu-utils qemu
      -
        name: run ./build.sh
        run: ./build.sh