name: ci

on:
  push:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: install deps
        run: sudo apt update && sudo apt install -y genisoimage qemu-kvm qemu-system-x86 gzip jq qemu-utils
      -
        name: run ./build.sh
        run: ./build.sh